export const Country = [
    {value: "notselected", text: ""},
    {value: "1", text: "Afghanistan"},
    {value: "2", text: "Albania"},
    {value: "3", text: "Algeria"},
    {value: "4", text: "American Samoa"},
    {value: "5", text: "Andorra"},
    {value: "6", text: "Angola"},
    {value: "7", text: "Anguilla"},
    {value: "8", text: "Antarctica"},
    {value: "9", text: "Antigua And Barbuda"},
    {value: "10", text: "Argentina"},
    {value: "11", text: "Armenia"},
    {value: "12", text: "Aruba"},
    {value: "13", text: "Australia"},
    {value: "14", text: "Austria"},
    {value: "15", text: "Azerbaijan"},
    {value: "16", text: "Bahamas"},
    {value: "17", text: "Bahrain"},
    {value: "18", text: "Bangladesh"},
    {value: "19", text: "Barbados"},
    {value: "20", text: "Belarus"},
    {value: "21", text: "Belgium"},
    {value: "22", text: "Belize"},
    {value: "23", text: "Benin"},
    {value: "24", text: "Bermuda"},
    {value: "25", text: "Bhutan"},
    {value: "26", text: "Bolivia"},
    {value: "27", text: "Bosnia and Herzegowina"},
    {value: "28", text: "Botswana"},
    {value: "29", text: "Bouvet Island"},
    {value: "30", text: "Brazil"},
    {value: "31", text: "British Indian Ocean Territory"},
    {value: "32", text: "Brunei Darussalam"},
    {value: "33", text: "Bulgaria"},
    {value: "34", text: "Burkina Faso"},
    {value: "35", text: "Burma"},
    {value: "36", text: "Burundi"},
    {value: "37", text: "Cambodia"},
    {value: "38", text: "Cameroon"},
    {value: "39", text: "Canada"},
    {value: "40", text: "Cape Verde"},
    {value: "41", text: "Cayman Islands"},
    {value: "42", text: "Central African Republic"},
    {value: "43", text: "Chad"},
    {value: "44", text: "Chile"},
    {value: "45", text: "China"},
    {value: "46", text: "Christmas Island"},
    {value: "47", text: "Cocos (Keeling) Islands"},
    {value: "48", text: "Colombia"},
    {value: "49", text: "Comoros"},
    {value: "50", text: "Congo"},
    {value: "51", text: "Congo, the Democratic Republic of the"},
    {value: "52", text: "Cook Islands"},
    {value: "53", text: "Costa Rica"},
    {value: "54", text: "Cote d'Ivoire"},
    {value: "55", text: "Croatia"},
    {value: "56", text: "Cuba"},
    {value: "57", text: "Cyprus"},
    {value: "58", text: "Czech Republic"},
    {value: "59", text: "Denmark"},
    {value: "60", text: "Djibouti"},
    {value: "61", text: "Dominica"},
    {value: "62", text: "Dominican Republic"},
    {value: "63", text: "East Timor"},
    {value: "64", text: "Ecuador"},
    {value: "65", text: "Egypt"},
    {value: "66", text: "El Salvador"},
    {value: "67", text: "England"},
    {value: "68", text: "Equatorial Guinea"},
    {value: "69", text: "Eritrea"},
    {value: "71", text: "Estonia"},
    {value: "72", text: "Ethiopia"},
    {value: "73", text: "Falkland Islands"},
    {value: "74", text: "Faroe Islands"},
    {value: "75", text: "Fiji"},
    {value: "76", text: "Finland"},
    {value: "77", text: "France"},
    {value: "78", text: "French Guiana"},
    {value: "79", text: "French Polynesia"},
    {value: "80", text: "French Southern Territories"},
    {value: "81", text: "Gabon"},
    {value: "82", text: "Gambia"},
    {value: "83", text: "Georgia"},
    {value: "84", text: "Germany"},
    {value: "85", text: "Ghana"},
    {value: "86", text: "Gibraltar"},
    {value: "88", text: "Greece"},
    {value: "89", text: "Greenland"},
    {value: "90", text: "Grenada"},
    {value: "91", text: "Guadeloupe"},
    {value: "92", text: "Guam"},
    {value: "93", text: "Guatemala"},
    {value: "245", text: "Guernsey"},
    {value: "94", text: "Guinea"},
    {value: "95", text: "Guinea-Bissau"},
    {value: "96", text: "Guyana"},
    {value: "97", text: "Haiti"},
    {value: "98", text: "Heard and Mc Donald Islands"},
    {value: "99", text: "Honduras"},
    {value: "100", text: "Hong Kong"},
    {value: "101", text: "Hungary"},
    {value: "102", text: "Iceland"},
    {value: "103", text: "India"},
    {value: "104", text: "Indonesia"},
    {value: "108", text: "Iran"},
    {value: "109", text: "Iraq"},
    {value: "105", text: "Ireland"},
    {value: "251", text: "Isle of Man"},
    {value: "106", text: "Israel"},
    {value: "107", text: "Italy"},
    {value: "110", text: "Jamaica"},
    {value: "111", text: "Japan"},
    {value: "250", text: "Jersey"},
    {value: "112", text: "Jordan"},
    {value: "113", text: "Kazakhstan"},
    {value: "114", text: "Kenya"},
    {value: "115", text: "Kiribati"},
    {value: "116", text: "Korea, Republic of"},
    {value: "249", text: "Kosovo"},
    {value: "118", text: "Kuwait"},
    {value: "119", text: "Kyrgyzstan"},
    {value: "120", text: "Lao People's Democratic Republic"},
    {value: "121", text: "Latvia"},
    {value: "122", text: "Lebanon"},
    {value: "123", text: "Lesotho"},
    {value: "124", text: "Liberia"},
    {value: "125", text: "Liechtenstein"},
    {value: "126", text: "Lithuania"},
    {value: "127", text: "Luxembourg"},
    {value: "128", text: "Macau"},
    {value: "129", text: "Macedonia"},
    {value: "130", text: "Madagascar"},
    {value: "131", text: "Malawi"},
    {value: "132", text: "Malaysia"},
    {value: "133", text: "Maldives"},
    {value: "134", text: "Mali"},
    {value: "135", text: "Malta"},
    {value: "136", text: "Marshall Islands"},
    {value: "137", text: "Martinique"},
    {value: "138", text: "Mauritania"},
    {value: "139", text: "Mauritius"},
    {value: "140", text: "Mayotte"},
    {value: "141", text: "Mexico"},
    {value: "142", text: "Micronesia, Federated States of"},
    {value: "143", text: "Moldova, Republic of"},
    {value: "144", text: "Monaco"},
    {value: "145", text: "Mongolia"},
    {value: "248", text: "Montenegro"},
    {value: "146", text: "Montserrat"},
    {value: "147", text: "Morocco"},
    {value: "148", text: "Mozambique"},
    {value: "149", text: "Myanmar"},
    {value: "150", text: "Namibia"},
    {value: "151", text: "Nauru"},
    {value: "152", text: "Nepal"},
    {value: "153", text: "Netherlands"},
    {value: "154", text: "Netherlands Antilles"},
    {value: "155", text: "New Caledonia"},
    {value: "156", text: "New Zealand"},
    {value: "157", text: "Nicaragua"},
    {value: "158", text: "Niger"},
    {value: "159", text: "Nigeria"},
    {value: "160", text: "Niue"},
    {value: "161", text: "Norfolk Island"},
    {value: "162", text: "Northern Ireland"},
    {value: "163", text: "Northern Mariana Islands"},
    {value: "164", text: "Norway"},
    {value: "165", text: "Oman"},
    {value: "166", text: "Pakistan"},
    {value: "167", text: "Palau"},
    {value: "168", text: "Panama"},
    {value: "169", text: "Papua New Guinea"},
    {value: "170", text: "Paraguay"},
    {value: "171", text: "Peru"},
    {value: "172", text: "Philippines"},
    {value: "173", text: "Pitcairn"},
    {value: "174", text: "Poland"},
    {value: "175", text: "Portugal"},
    {value: "176", text: "Puerto Rico"},
    {value: "177", text: "Qatar"},
    {value: "178", text: "Reunion"},
    {value: "179", text: "Romania"},
    {value: "180", text: "Russia"},
    {value: "181", text: "Rwanda"},
    {value: "182", text: "Saint Kitts and Nevis"},
    {value: "183", text: "Saint Lucia"},
    {value: "184", text: "Saint Vincent and the Grenadines"},
    {value: "185", text: "Samoa (Independent)"},
    {value: "186", text: "San Marino"},
    {value: "187", text: "Sao Tome and Principe"},
    {value: "188", text: "Saudi Arabia"},
    {value: "189", text: "Scotland"},
    {value: "190", text: "Senegal"},
    {value: "247", text: "Serbia"},
    {value: "191", text: "Serbia and Montenegro"},
    {value: "192", text: "Seychelles"},
    {value: "193", text: "Sierra Leone"},
    {value: "194", text: "Singapore"},
    {value: "195", text: "Slovakia"},
    {value: "196", text: "Slovenia"},
    {value: "197", text: "Solomon Islands"},
    {value: "198", text: "Somalia"},
    {value: "199", text: "South Africa"},
    {value: "200", text: "South Georgia and the South Sandwich Islands"},
    {value: "201", text: "South Korea"},
    {value: "202", text: "Spain"},
    {value: "203", text: "Sri Lanka"},
    {value: "204", text: "St. Helena"},
    {value: "205", text: "St. Pierre and Miquelon"},
    {value: "246", text: "Sudan, Republic of"},
    {value: "206", text: "Suriname"},
    {value: "207", text: "Svalbard and Jan Mayen Islands"},
    {value: "208", text: "Swaziland"},
    {value: "209", text: "Sweden"},
    {value: "210", text: "Switzerland"},
    {value: "211", text: "Taiwan"},
    {value: "212", text: "Tajikistan"},
    {value: "213", text: "Tanzania"},
    {value: "214", text: "Thailand"},
    {value: "215", text: "Togo"},
    {value: "216", text: "Tokelau"},
    {value: "217", text: "Tonga"},
    {value: "218", text: "Trinidad"},
    {value: "219", text: "Trinidad and Tobago"},
    {value: "220", text: "Tunisia"},
    {value: "221", text: "Turkey"},
    {value: "222", text: "Turkmenistan"},
    {value: "223", text: "Turks and Caicos Islands"},
    {value: "224", text: "Tuvalu"},
    {value: "225", text: "Uganda"},
    {value: "226", text: "Ukraine"},
    {value: "227", text: "United Arab Emirates"},
    {value: "228", text: "United Kingdom"},
    {value: "229", text: "United States"},
    {value: "230", text: "United States Minor Outlying Islands"},
    {value: "231", text: "Uruguay"},
    {value: "232", text: "Uzbekistan"},
    {value: "233", text: "Vanuatu"},
    {value: "234", text: "Vatican City State (Holy See)"},
    {value: "235", text: "Venezuela"},
    {value: "236", text: "Viet Nam"},
    {value: "237", text: "Virgin Islands (British)"},
    {value: "238", text: "Virgin Islands (U.S.)"},
    {value: "239", text: "Wales"},
    {value: "240", text: "Wallis and Futuna Islands"},
    {value: "241", text: "Western Sahara"},
    {value: "242", text: "Yemen"},
    {value: "243", text: "Zambia"},
    {value: "244", text: "Zimbabwe"}
];

export const getCountryName = function (countryvalue: string) {
    const countryObj = Country.find((element) => element.value === countryvalue);
    if (countryObj !== undefined) {
        return countryObj.text;
    } else {
        return "";
    }
};
